version: "3"
services:
  backend:
    image: chanhee01/auto-meet
    container_name: AutoMeet_backend
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: AutoMeet
      MYSQL_URL: $MYSQL_URL
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    restart: always

  openvidu:
    image: openvidu/openvidu-server-kms:2.23.0
    container_name: OpenVidu
    ports:
      - "4443:4443"
      - "8888:8888"
    environment:
      openvidu.publicurl: http://54.180.44.62:4443
      OPENVIDU_SECRET: AutoMeet
    restart: always