version: "3"
services:
  backend:
    image: chanhee01/auto-meet
    container_name: AutoMeet_backend
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: $JWT_SECRET
      MYSQL_URL: $MYSQL_URL
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    restart: always

  openvidu:
    image: openvidu/openvidu-server-kms:latest
    container_name: OpenVidu
    ports:
      - "4443:4443"
      - "8888:8888"
    restart: always