version: "3"
services:
  backend:
    image: chanhee01/auto-meet
    container_name: AutoMeet_backend
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: AutoMeet
      MYSQL_URL: $MYSQL_URL
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    restart: always