# mysql
spring :
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.jdbc.time_zone: Asia/Seoul

  # mongodb
  data :
    mongodb :
      uri : mongodb+srv://joch4267:${MYSQL_PASSWORD}@automeet-cluster.obyp0ni.mongodb.net/?retryWrites=true&w=majority&appName=AutoMeet-Cluster

mongo.uri : mongodb+srv://joch4267:${MYSQL_PASSWORD}@automeet-cluster.obyp0ni.mongodb.net/?retryWrites=true&w=majority&appName=AutoMeet-Cluster

jwt.secret : ${JWT_SECRET}


# openvidu
OPENVIDU_URL : http://3.35.93.214:4443
OPENVIDU_SECRET : AutoMeet

